name: make terraform plan
on: [push]

jobs:
  make-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: €{{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: €{{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: €{{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Initialize Terraform
        id: init
        run: terraform init
        # env:
        #   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
        #   ARM_CLIENT_SECRET: €{{ secrets.ARM_CLIENT_SECRET }}
        #   ARM_TENANT_ID: €{{ secrets.ARM_TENANT_ID }}
        #   ARM_SUBSCRIPTION_ID: €{{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true